#!/bin/zsh

# Use included files to set up iTerm

# First, install oh-my-zsh:
# https://ohmyz.sh

# Install nerdfonts:
# https://github.com/ryanoasis/nerd-fonts#option-4-homebrew-fonts

# Then, install powerline10k:
# git clone --depth=1 https://github.com/romkatv/powerlevel10k.git $ZSH/themes/powerlevel10k

# Install zsh-autosuggestions
# https://github.com/zsh-users/zsh-autosuggestions

# Install zsh-syntax-highlighting
# https://github.com/zsh-users/zsh-syntax-highlighting

# Install exa
# https://the.exa.website

# Set theme:
# ZSH_THEME="powerlevel10k/powerlevel10k"

# Set plugins:
# plugins=(
#   git
#   zsh-autosuggestions
#   zsh-syntax-highlighting
# )

# Remove .p10k.zsh and .vimrc from home directory
# Map .vimrc here with ln -s
